on:
  push:
    branches: remotedev

name: docs-remotedev

jobs:
  docs-remotedev:
    name: Update docs
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Query dependencies
        run: |
          install.packages('remotes')
          install.packages('devtools')
          install.packages('styler')
          install.packages('roxygen2')
          install.packages('codemetar')
          install.packages('jsonld')
          install.packages('ragg')
          install.packages('usethis')
          
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          
      - name: Install package
        run: Rscript -e 'devtools::install()'
        
      - name: Description
        run: Rscript -e 'usethis::use_tidy_description()'
        
      - name: Style
        run: Rscript -e 'styler::style_pkg()'

      - name: Roxygenise
        run: Rscript -e 'roxygen2::roxygenise()'
        
      - name: Render README
        run: Rscript -e 'devtools::build_readme()'
        
      - name: Codemetar
        run: |
          Rscript -e 'codemetar::write_codemeta(write_minimeta = TRUE)'
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Update docs' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
